name: Run Shortcut to Google Sheets

on:
  schedule:
    - cron: '0 22 * * *' # 23:00 CET (22:00 UTC)
  workflow_dispatch: # Allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.1.0'

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Run script
        run: node dist/script.js
        env:
          SHORTCUT_API_TOKEN: ${{ secrets.SHORTCUT_API_TOKEN }}
          GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}